spring:
  application:
    name: SmartGazalBee
  datasource:
      url: jdbc:mysql://localhost:3306/SmartGazalBee?useSSL=false&serverTimezone=Asia/Seoul
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/desktop/hanium/SmartGazalBee
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create #??? ? create, ??? ? none?? ???
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  profiles:
    include: private


logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

server:
  address: localhost #?? ? localhost? ??, ?? ? ?? ip ???? kakao developers?? login-logout redirect uri? private.yml ??
  port: 8080